title: Somagenesis
owner: Joseph J.G.
email:
description: Reviews, essays, and thoughts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username:
github_username:
disqus_username: 
# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

paginate: 10

paginate_multiple:
  - paginate: 1
    paginate_path: '/categories/reviews/page:num/'

gems:
  - jekyll-feed
  - jekyll-paginate-multiple
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
