title: Somagenesis
owner:
email:
description: Reviews, essays, and thoughts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username:
github_username:
disqus_username: 
# Build settings
markdown: kramdown
theme: minima

permalink: /:year/:month/:day/:title/

paginate: 5

gems:
  - jekyll-feed
  - jekyll-paginate-v2
plugins:
  - jekyll-paginate-v2
exclude:
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
